### ISSUE TITLE
Update needed in SvelteKit - GraphQL Request example

### ISSUE THREAD

**Issue by PimTournaye** [hygraph/hygraph-examples#242]
Breaking change from a couple of months ago
[Relevant pull request in the Sveltekit repo](https://github.com/sveltejs/kit/pull/3126)

The following error is given in [slug].svelte

```
page` in `load` functions has been replaced by `url` and `params
```

**Comment by notrab** [comment]
I'd be happy to merge a PR if you want to tackle this @PimTournaye ?
